[project]
name = "snkmt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Cade Mirchandani", email = "cmirchan@ucsc.edu" }]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
snkmt = "snkmt:main"

[tool.uv.sources]
snakemake-logger-plugin-snkmt = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
snkmt = { path = ".", editable = true }

[tool.pixi.tasks]
