[project]
name = "snakemake-logger-plugin-snkmt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Cade Mirchandani", email = "cmirchan@ucsc.edu" }]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
    "snakemake-interface-logger-plugins>=1.2.0",
    "sqlalchemy>=2.0.38",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "snakemake>=9.0.1",
    "ruff>=0.9.10",
    "loguru>=0.7.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/snakemake_logger_plugin_snkmt"]